

const gameSeed = [{
    title: "Tetris Effect",
    system: "PS4",
    developer: "Enhance Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/3059453-image.jpeg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:12
},
{
    title: "BioShock Infinite",
    system: "PS3",
    developer: "Irrational Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2379677-bioshockinfinite_boxart.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:13
},
{
    title: "Metroid: Zero Mission",
    system: "GBA",
    developer: "Nintendo",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2617564-mzm.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:14
},{
    title: "Tetris Effect",
    system: "PS4",
    developer: "Enhance Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/3059453-image.jpeg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:15
},
{
    title: "BioShock Infinite",
    system: "PS3",
    developer: "Irrational Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2379677-bioshockinfinite_boxart.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:16
},
{
    title: "Metroid: Zero Mission",
    system: "GBA",
    developer: "Nintendo",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2617564-mzm.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:17
},{
    title: "Tetris Effect",
    system: "PS4",
    developer: "Enhance Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/3059453-image.jpeg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:18
},
{
    title: "BioShock Infinite",
    system: "PS3",
    developer: "Irrational Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2379677-bioshockinfinite_boxart.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:19
},
{
    title: "Metroid: Zero Mission",
    system: "GBA",
    developer: "Nintendo",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2617564-mzm.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:20
},{
    title: "Tetris Effect",
    system: "PS4",
    developer: "Enhance Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/3059453-image.jpeg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:21,
},
{
    title: "BioShock Infinite",
    system: "PS3",
    developer: "Irrational Games",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2379677-bioshockinfinite_boxart.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:23
},
{
    title: "Metroid: Zero Mission",
    system: "GBA",
    developer: "Nintendo",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2617564-mzm.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:24
},
{
    title: "Metroid: Zero Mission",
    system: "GBA",
    developer: "Nintendo",
    box_art: "https://www.giantbomb.com/api/image/scale_medium/2617564-mzm.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    id:11
}
]

export default gameSeed