

const gameSeed = [{
    title: "Tetris Effect",
    system_type: "PS4",
    developer: "Enhance Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:12
},
{
    title: "BioShock Infinite",
    system_type: "PS3",
    developer: "Irrational Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:13
},
{
    title: "Metroid: Zero Mission",
    system_type: "GBA",
    developer: "Nintendo",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:14
},{
    title: "Tetris Effect",
    system_type: "PS4",
    developer: "Enhance Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:15
},
{
    title: "BioShock Infinite",
    system_type: "XONE",
    developer: "Irrational Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:16
},
{
    title: "Metroid: Zero Mission",
    system_type: "GBA",
    developer: "Nintendo",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:17
},{
    title: "Tetris Effect",
    system_type: "PS4",
    developer: "Enhance Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:18
},
{
    title: "Super Smash Bros",
    system_type: "NSW",
    developer: "Irrational Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:19
},
{
    title: "Xenoblade X",
    system_type: "WiiU",
    developer: "Nintendo",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:20
},{
    title: "Tetris Effect",
    system_type: "PS4",
    developer: "Enhance Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "Tetris for the PS4/PSVR by Tetsuya Mizuguchi, creator of REZ and Lumines.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    owned: true,
    rating: 9.5,
    price: 40,
    year_released: 2018,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:21,
},
{
    title: "BioShock Infinite",
    system_type: "PS3",
    developer: "Irrational Games",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "The third game in the BioShock series leaves the bottom of the sea behind for an entirely new setting - the floating city of Columbia, circa 1912. Come to retrieve a girl named Elizabeth, ex-detective Booker DeWitt finds more in store for him there than he could ever imagine.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 10,
    price: 10,
    year_released: 2013,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:23
},
{
    title: "Mario Sunshine",
    system_type: "GCN",
    developer: "Nintendo",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:24
},
{
    title: "Metroid: Zero Mission",
    system_type: "GBA",
    developer: "Nintendo",
    box_art: "https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Super_Smash_Bros._Ultimate.jpg/220px-Super_Smash_Bros._Ultimate.jpg",
    description: "A GBA Metroid game and remake of the original Metroid for the NES. It also depicts what happens immediately after the self destruct sequence by Mother Brain.",
    is_beaten: true,
    favorite: true,
    now_playing: false,
    rating: 9.5,
    price: 25,
    year_released: 2004,
    date: new Date(Date.now()),
    user: "Justin",
    note: "testing",
    _id:11
}
]

export default gameSeed